### ISSUE TITLE
Typo in net.osgiliath.features.karaf-features-monitoring.xml

### ISSUE THREAD

**Issue by garyhodgson** [OsgiliathEnterprise/net.osgiliath.parent#49]
osgliath-war should be osgiliath-war

**Comment by Tcharl** [comment]
Well done gary.
I will include this change for sure :).
Want you become a contributor/team member?

**Comment by garyhodgson** [comment]
Hi,  It's too early to consider being a contributor :) but I'll definitely contribute whatever I can as I play with the framework.  You've pulled together the same technology stack I was planning on trying out for my company and so I will definitely be trying things out.

**Comment by Tcharl** [comment]
Glad to ear this :).

If your integration succeed, can you tell me so? I planned to make Osgiliath a Karaf sub-project (like Cave, Decanter, etc..), but its lack of company adoption (3 small sized for the moment) didn't convince the Karaf PMC (its the only blocking point).

As for contribution, I'll duplicate my internal redmine tickets to the github one, so that you'll be free to contribute by PR if you want (in a first time). In addition, don't be shy to post feature requests if you want some, I'll be glad to help.

Best regards
